### ISSUE TITLE
🚀 Version Control  support to disable speculative plans

### ISSUE THREAD

**Issue by KamalAman** [hashicorp/terraform-cloud-operator#238]
### Description

Add support to configure if a workspace should trigger speculative plans for pull requests to the repository.

https://developer.hashicorp.com/terraform/cloud-docs/workspaces/settings/vcs#automatic-speculative-plans

I dont know what the API looks like, I cannot find clear documentation, but it should be possible. 

I would like to disable speculative plans for my workspaces

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by arybolovlev** [comment]
Hi @KamalAman,

I am currently working on this. It would be a workspace-level feature rather than just a version control. This is how it works on the API level and I want to double-check how it would be compatible with CLI and API-driven workflows.

Here is an example:

```yaml
spec:
  ...
  speculativePlan: false
```

Default to `true` to keep backward compatibility.

_The result name might change._

Thanks!

**Comment by arybolovlev** [comment]
I will move `speculativePlan` under `versionControl` since it affects only VCS settings even though it is applied on the Workspace level:

```yaml
spec:
  ...
  versionControl:
    speculativePlan: < true | false >
```
